### ISSUE TITLE
GoGo Protobuf is deprecated

### ISSUE THREAD

**Issue by swamisriman** [signalfx/com_signalfx_metrics_protobuf#15]
As GoGo Protobuf is deprecated, are there any plans to refactor these proto files to standard .proto files?

Ref: https://github.com/gogo/protobuf/tree/master

Looks like GoGo Protobuf is mandatory to compile this source.
Currently, when trying to compile the proto, I get this error
```
$ protoc -I=$SRC_DIR --python_out=$DST_DIR $SRC_DIR/signalfx_metrics.proto
gogoproto/gogo.proto: File not found.
signalfx_metrics.proto:5:1: Import "gogoproto/gogo.proto" was not found or had errors.
```

**Comment by atoulme** [comment]
You can use `make proto` to generate code, it will take care of imports. GoGo Protobuf is indeed deprecated but continues to work for the purposes of this project.

This project will be archived. Please consider opening a support ticket for any further communication.
