### ISSUE TITLE
Appears to be broken with the latest protobuf

### ISSUE THREAD

**Issue by msonnabaum** [signalfx/com_signalfx_metrics_protobuf#2]
Trying to use the go client I immediately get these errors:

```
$ go get github.com/signalfx/golib/sfxclient
# github.com/signalfx/com_signalfx_metrics_protobuf
~/.go/src/github.com/signalfx/com_signalfx_metrics_protobuf/signal_fx_protocol_buffers.pb.go:445: undefined: proto.RegisterType
~/.go/src/github.com/signalfx/com_signalfx_metrics_protobuf/signal_fx_protocol_buffers.pb.go:446: undefined: proto.RegisterType
~/.go/src/github.com/signalfx/com_signalfx_metrics_protobuf/signal_fx_protocol_buffers.pb.go:447: undefined: proto.RegisterType
~/.go/src/github.com/signalfx/com_signalfx_metrics_protobuf/signal_fx_protocol_buffers.pb.go:448: undefined: proto.RegisterType
~/.go/src/github.com/signalfx/com_signalfx_metrics_protobuf/signal_fx_protocol_buffers.pb.go:449: undefined: proto.RegisterType
~/.go/src/github.com/signalfx/com_signalfx_metrics_protobuf/signal_fx_protocol_buffers.pb.go:450: undefined: proto.RegisterType
~/.go/src/github.com/signalfx/com_signalfx_metrics_protobuf/signal_fx_protocol_buffers.pb.go:451: undefined: proto.RegisterType
~/.go/src/github.com/signalfx/com_signalfx_metrics_protobuf/signal_fx_protocol_buffers.pb.go:452: undefined: proto.RegisterType
~/.go/src/github.com/signalfx/com_signalfx_metrics_protobuf/signal_fx_protocol_buffers.pb.go:453: undefined: proto.RegisterType
```

I'm guessing that the file in this repo just needs to be regenerated with the latest protobuf.

Also, I was going to try to regenerate it myself, but I couldn't find where the proto file is, if it's hosted publicly at all. It would be nice if this repo provided some documentation on how to regenerate it.

**Comment by mdubbyap** [comment]
Hey Mark, which version of go are you using?  I tried this on a fresh ubuntu vm with go 1.6 and a blank GOPATH, and it worked perfectly.  Is it possible that one of the dependencies is already in your GOPATH but not up to date.  Did you try with go get -u ?

To answer your question on the .proto file is located at https://github.com/signalfx/signalfx-java/blob/master/signalfx-protoc/src/main/protobuf/signal_fx_protocol_buffers.proto. 

I'll verify that they're up to date, but iirc they are.

**Comment by cep21** [comment]
@mdubbyap 3.0.0 was released just a few days ago.  It may have changed some stuff (https://github.com/google/protobuf/releases/tag/v3.0.0)

**Comment by msonnabaum** [comment]
It would appear that @mdubbyap is correct. I deleted `~/.go/src/github.com/golang/protobuf`, re-downloaded the client, and it worked fine.

Yay Go having no concept of package versions 👍
